//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawOnMe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawOnMe.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string AboutSentence {
            get {
                return ResourceManager.GetString("AboutSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have noticed any lack of functionality or any bug of the Fit&amp;Gym app, let me know about it.
        ///
        ///Your information won&apos;t be ignored.
        ///
        ///PS. Rates and comments will be welcome ;).
        /// </summary>
        public static string AdditionalContentOfAboutBox {
            get {
                return ResourceManager.GetString("AdditionalContentOfAboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw On Me.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bg color.
        /// </summary>
        public static string BgColorTextBlock {
            get {
                return ResourceManager.GetString("BgColorTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string ClearAppBar {
            get {
                return ResourceManager.GetString("ClearAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szbartnik@gmail.com.
        /// </summary>
        public static string CreatorEmail {
            get {
                return ResourceManager.GetString("CreatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szymon Bartnik.
        /// </summary>
        public static string CreatorNameAndSurname {
            get {
                return ResourceManager.GetString("CreatorNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and created by.
        /// </summary>
        public static string DesignedAndCreatedBySentence {
            get {
                return ResourceManager.GetString("DesignedAndCreatedBySentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about app.
        /// </summary>
        public static string InfoAppBar {
            get {
                return ResourceManager.GetString("InfoAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        public static string LineColorTextBlock {
            get {
                return ResourceManager.GetString("LineColorTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line thickness.
        /// </summary>
        public static string LineThicknessTextBlock {
            get {
                return ResourceManager.GetString("LineThicknessTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load image.
        /// </summary>
        public static string OpenAppBar {
            get {
                return ResourceManager.GetString("OpenAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate app.
        /// </summary>
        public static string RateAppBar {
            get {
                return ResourceManager.GetString("RateAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveAppBar {
            get {
                return ResourceManager.GetString("SaveAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        public static string UndoAppBar {
            get {
                return ResourceManager.GetString("UndoAppBar", resourceCulture);
            }
        }
    }
}
